import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.scss'
import { Logo } from './components/Logo'
import { Layout } from './components/Layout'
import ArrowLink from './components/ArrowLink'

export default function Home() {
  return (
    <Layout fromTop>
      <div className={styles.Container}>
        <Head>
          <title>Adson Formiga</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Logo />

        <nav className={styles.Navigation}>
          <ul>
            <li className={styles.ItemRight}>
              <ArrowLink label="contato" link="/contato" right />
            </li>
            <li className={styles.ItemLeft}>
              <ArrowLink label="designs" link="/meu-trabalho" left />
            </li>
            <li className={styles.ItemBottom}>
              <ArrowLink label="sobre mim" link="/sobre-mim" bottom />
            </li>
          </ul>
        </nav>
      </div>
    </Layout>
  )
}
