import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Logo } from './components/Logo'

export default function Home() {
  return (
    <div className={styles.Container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo />

      <nav>
        <ul>
          <li className={styles.ItemRight}>
            <a href="/contato">contato</a>
          </li>
        </ul>
      </nav>
    </div>
  )
}
